main/account/urls.py
from django.urls import path
from account.views import ( user_registration_view,
                            login_view, logout_view,
                            account_view )


app_name = 'account'
urlpatterns = [
    path('register/', user_registration_view, name='register_user'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('<username>/', account_view, name='profile')
]

main/bookapp/urls.py
from django.urls import path
from bookapp.views import (BldgRegistrationView,
                           RoomBldgListView,
                           RoomRegistrationView,
                           BookedRoomView,
                           CheckedOutView,
                           RoomView,
                        #    BookRoomView
                            )

app_name = 'bookapp'
urlpatterns = [
    path('building/register', BldgRegistrationView.as_view(), name='bldg_register'),
    path('building/room/register', RoomRegistrationView.as_view(), name='add_room'),
    path('', RoomBldgListView.as_view(), name='room_bldg_list'),
    path('booked/', BookedRoomView.as_view(), name='booked'),
    path('booked/<int:id>/', CheckedOutView.as_view(), name='checkout'),
    path('book-a-room/', RoomView.as_view(), name='book_a_room'),
    path('room/<int:id>/', RoomView.as_view(), name='room_data'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('account/', include('account.urls')),
    path('home/', include('bookapp.urls')),


    path('api/book/', include('bookapp.api.urls')),
    path('api/account/', include('account.api.urls')),

    path('admin/', admin.site.urls),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/templates/snippets/base_css.html
<style>
* {
    margin: 0;
    padding: 0;
}

html, body {
    height: 100%;
}

.wrapper {
    display: flex;
    flex-direction: column;
    /* min-height: 100vh; */
}

main {
    flex: 1;
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}

</style>

main/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 70px;
		margin-top: auto;
		padding: 10px;
		background-color: #286d71;
		color: white;
	}
	.footer_p{
		text-align: center;
		margin: auto;
		font-size: 13px;
		width: 50%;
	}
</style>
<div class="d-flex flex-row align-items-center footer shadow-lg">
	<p class="footer_p">Looking for a comfortable stay? Book your room now and enjoy our exceptional hospitality. Whether it's for business or leisure, we have the perfect accommodation for you. Contact us today to reserve your room or suite.</p>
</div>

main/templates/snippets/navbar.html
<!-- Header -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

	<!-- MEDIUM+ SCREENS -->
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark text-decoration-none" href="{% url 'bookapp:room_bldg_list' %}">Home</a>
		</h5>
		{% if request.user.username == 'admin' %}
		<h5 class="mr-3 justify-content-start ms-2">
		<a class="p-2 text-dark text-decoration-none" href="{% url 'bookapp:bldg_register'%}">New Building</a>
		</h5>
		<h5 class="mr-3 justify-content-start ms-2">
		<a class="p-2 text-dark text-decoration-none" href="{% url 'bookapp:add_room' %}">Add Room</a>
		</h5>
		<h5 class="mr-3 justify-content-start ms-2">
			<a class="p-2 text-dark text-decoration-none" href="{% url 'bookapp:booked' %}">Booked Room</a>
		</h5>
		{% endif %}

		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
						<div class="d-flex flex-row">
							<div>
								<a class="nav-link" href="{% url 'account:profile' request.user.username %}">{{ request.user.username }}</a>
							</div>
							<div>
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="codingwithmitch logo" width="40" height="40">
							</div>
							<div>
								<a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
							</div>
						</div>
						</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'account:register_user' %}">Register</a>
				{% endif %}	
			</nav>
		</div>
	</div>
	<!-- END MEDIUM+ SCREENS -->

	<!-- SMALL SCREENS -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<h5 class="font-weight-normal">
		<a class="p-2 text-dark" href="{% url 'bookapp:room_bldg_list' %}">Home</a>
		</h5>
		{% if request.user.username == 'admin' %}
		<a href="{% url 'bookapp:bldg_register'%}">Register New Building</a>
		<a href="{% url 'bookapp:add_room' %}">Add Room</a>
		<a class="p-2 text-dark text-decoration-none" href="{% url 'bookapp:booked' %}">Booked Room</a>
		{% endif %}
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="codingwithmitch logo" width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="{% url 'account:profile' request.user.username %}">{{ request.user.username }}</a>
								<a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
					<a class="btn btn-outline-primary m-2" href="{% url 'account:register_user' %}">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
</div>